import Link from "next/link";
import "./globals.css";
import Footer from "./sections/footer/Footer";
import Header from "./sections/header/Header";
import "jquery";
import Script from "next/script";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <header>
          <Header />
          <Script src="/js/smoothScroll.js" strategy="afterInteractive" />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
          <div className="text-center text-gray-500 bg-gray-950 py-5 flex justify-center gap-4 flex-wrap">
            <p className="">&copy; 2024</p>
            <Link
              href="/privacyPolicy"
              className="hover:text-white transition duration-150 ease-linear"
            >
              Privacy Policy
            </Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
